version: "2.1"

commands:
  install_aws_cli_tools:
    description: >
      Install aws cli tools for publishing the build to s3 and manipulating cloudfront, our CDN
    steps:
      - run:
          name: Download Pip
          command: curl -O https://bootstrap.pypa.io/get-pip.py
      - run:
          name: Install Pip
          command: python3 get-pip.py --user
      - run:
          name: Install aws cli tools
          command: pip3 install awscli --upgrade --user

jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn ci
  publish:
    docker:
      - image: circleci/node:lts
    steps:
      - install_aws_cli_tools
      - run: which aws
    branches:
      only: bs_clockface_cdn
